In [1]:

# 행정동 데이터 전처리요~


In [145]:
import numpy as np
import pandas as pd
import os
from glob import glob


In [146]:
df_total=pd.DataFrame()

df_거주인구=pd.DataFrame()
df_상주인구=pd.DataFrame()
df_생활인구=pd.DataFrame()
df_소득소비=pd.DataFrame()
df_아파트=pd.DataFrame()
df_영역=pd.DataFrame()
df_점포=pd.DataFrame()
df_직장인구=pd.DataFrame()
df_집객시설=pd.DataFrame()
df_추정매출=pd.DataFrame()
df_학교=pd.DataFrame()



In [147]:
path='../../../big_proj/data/raw data/행정동/'


In [148]:
pwd

'c:\\Users\\user\\big_proj\\project-file\\Modeling'

In [6]:
# # 거주인구
# dfs_거주인구=[]
# for f_name in glob(path+'거주인구/*.csv'):
#     temp=pd.read_csv(f_name)
#     dfs_거주인구.append(temp)
#     # df_거주인구=pd.concat([df_거주인구,temp],)
# a,b,c,d=dfs_거주인구

# print(a.shape,b.shape,c.shape,d.shape)


(452, 15) (453, 15) (454, 15) (454, 15)


In [149]:
# 상주인구
dfs_상주인구=[]
for f_name in glob(path+'상주인구/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_상주인구.append(temp)
df_상주인구,=dfs_상주인구

df_상주인구.head()

기준_년분기_코드    행정동_코드 행정동_코드_명  총_상주인구_수  남성_상주인구_수  여성_상주인구_수  \
0      20191  11110515    청운효자동     13047       6111       6936   
1      20191  11110530      사직동      9224       4169       5055   
2      20191  11110540      삼청동      2831       1344       1487   
3      20191  11110550      부암동     10055       4850       5205   
4      20191  11110560      평창동     18615       8775       9840   

   연령대_10_상주인구_수  연령대_20_상주인구_수  연령대_30_상주인구_수  연령대_40_상주인구_수  ...  \
0           2248           1648           1879           2304  ...   
1           1387           1095           1383           1558  ...   
2            340            336            422            399  ...   
3           1490           1394           1277           1647  ...   
4           3018           2691           2303           2848  ...   

   남성연령대_60_이상_상주인구_수  여성연령대_10_상주인구_수  여성연령대_20_상주인구_수  여성연령대_30_상주인구_수  \
0                1235             1052              821             1020   
1                1021              697              603              781   
2                 383              156              171              220   
3                1137              689              633              672   
4                1976             1472             1272             1231   

   여성연령대_40_상주인구_수  여성연령대_50_상주인구_수  여성연령대_60_이상_상주인구_수  총_가구_수  아파트_가구_수  \
0             1283             1062                1698    5384       314   
1              856              810                1308    4352       163   
2              201              253                 486    1413         0   
3              905              909                1397    4243        74   
4             1592             1757                2516    7463       459   

   비_아파트_가구_수  
0        5070  
1        4189  
2        1413  
3        4169  
4        7004  

[5 rows x 27 columns]

In [150]:
df_상주인구.shape

(7629, 27)

In [151]:
df_상주인구['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194, 20201, 20202, 20203, 20204, 20211,
       20212, 20213, 20214, 20221, 20222, 20224, 20231, 20232, 20223],
      dtype=int64)

In [152]:
df_상주인구.isna().sum()

기준_년분기_코드             0
행정동_코드                0
행정동_코드_명              0
총_상주인구_수              0
남성_상주인구_수             0
여성_상주인구_수             0
연령대_10_상주인구_수         0
연령대_20_상주인구_수         0
연령대_30_상주인구_수         0
연령대_40_상주인구_수         0
연령대_50_상주인구_수         0
연령대_60_이상_상주인구_수      0
남성연령대_10_상주인구_수       0
남성연령대_20_상주인구_수       0
남성연령대_30_상주인구_수       0
남성연령대_40_상주인구_수       0
남성연령대_50_상주인구_수       0
남성연령대_60_이상_상주인구_수    0
여성연령대_10_상주인구_수       0
여성연령대_20_상주인구_수       0
여성연령대_30_상주인구_수       0
여성연령대_40_상주인구_수       0
여성연령대_50_상주인구_수       0
여성연령대_60_이상_상주인구_수    0
총_가구_수                0
아파트_가구_수              0
비_아파트_가구_수            0
dtype: int64

In [159]:
temp_total=0
cnt=0
for x in df_상주인구['기준_년분기_코드'].unique():
    print("년분기:",x,end='  ')
    print(df_상주인구.loc[df_상주인구['기준_년분기_코드']==x]['기준_년분기_코드'].count(),end='  ')
    if cnt%7==0:
        print()
    cnt+=1
print("cnt:",cnt)

년분기: 20191  418  
년분기: 20192  418  년분기: 20193  418  년분기: 20194  425  년분기: 20201  425  년분기: 20202  425  년분기: 20203  425  년분기: 20204  425  
년분기: 20211  425  년분기: 20212  425  년분기: 20213  425  년분기: 20214  425  년분기: 20221  425  년분기: 20222  425  년분기: 20224  425  
년분기: 20231  425  년분기: 20232  425  년분기: 20223  425  cnt: 18


In [160]:
# 20191, 20192, 20193
dong_code_20191=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20191]['행정동_코드'])
dong_code_20192=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20192]['행정동_코드'])
dong_code_20193=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20193]['행정동_코드'])
dong_code_20194=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20194]['행정동_코드'])

In [161]:
diff_191=[x for x in dong_code_20194 if x not in dong_code_20191 ]
diff_192=[x for x in dong_code_20194 if x not in dong_code_20192 ]
diff_193=[x for x in dong_code_20194 if x not in dong_code_20193 ]
print(diff_191)
print(diff_192)
print(diff_193)
# 번1,2,3동/ 수유1,2,3동/ 항동

[11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800]
[11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800]
[11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800]


In [153]:
# 생활인구
dfs_생활인구=[]
for f_name in glob(path+'생활인구/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_생활인구.append(temp)
df_생활인구,=dfs_생활인구


In [154]:
df_생활인구.shape

(7650, 25)

In [155]:
df_생활인구['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194, 20201, 20202, 20203, 20204, 20211,
       20212, 20213, 20214, 20221, 20222, 20223, 20224, 20231, 20232],
      dtype=int64)

In [156]:
df_생활인구.isna().sum()

기준_년분기_코드           0
행정동_코드              0
행정동_코드_명            0
총_유동인구_수            0
남성_유동인구_수           0
여성_유동인구_수           0
연령대_10_유동인구_수       0
연령대_20_유동인구_수       0
연령대_30_유동인구_수       0
연령대_40_유동인구_수       0
연령대_50_유동인구_수       0
연령대_60_이상_유동인구_수    0
시간대_00_06_유동인구_수    0
시간대_06_11_유동인구_수    0
시간대_11_14_유동인구_수    0
시간대_14_17_유동인구_수    0
시간대_17_21_유동인구_수    0
시간대_21_24_유동인구_수    0
월요일_유동인구_수          0
화요일_유동인구_수          0
수요일_유동인구_수          0
목요일_유동인구_수          0
금요일_유동인구_수          0
토요일_유동인구_수          0
일요일_유동인구_수          0
dtype: int64

In [162]:
temp_total=0
cnt=0
for x in df_생활인구['기준_년분기_코드'].unique():
    print("년분기:",x,end='  ')
    print(df_생활인구.loc[df_생활인구['기준_년분기_코드']==x]['기준_년분기_코드'].count(),end='  ')
    if cnt%7==0:
        print()
    cnt+=1
print("cnt:",cnt)

년분기: 20191  425  
년분기: 20192  425  년분기: 20193  425  년분기: 20194  425  년분기: 20201  425  년분기: 20202  425  년분기: 20203  425  년분기: 20204  425  
년분기: 20211  425  년분기: 20212  425  년분기: 20213  425  년분기: 20214  425  년분기: 20221  425  년분기: 20222  425  년분기: 20223  425  
년분기: 20224  425  년분기: 20231  425  년분기: 20232  425  cnt: 18


In [27]:
# # 생활인구 merge
# df_total=pd.merge(df_생활인구,df_total,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])

In [28]:
# df_total.shape

(7650, 49)

In [163]:
# 소득소비
dfs_소득소비=[]
for f_name in glob(path+'소득소비/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_소득소비.append(temp)
df_소득소비,=dfs_소득소비

In [164]:
df_소득소비.shape

(7650, 16)

In [165]:
df_소득소비.isna().sum()

기준_년분기_코드       0
행정동_코드          0
행정동_코드_명        0
월_평균_소득_금액      0
소득_구간_코드        0
지출_총금액          0
식료품_지출_총금액      0
의류_신발_지출_총금액    0
생활용품_지출_총금액     0
의료비_지출_총금액      0
교통_지출_총금액       0
교육_지출_총금액       0
유흥_지출_총금액       0
여가_문화_지출_총금액    0
기타_지출_총금액       0
음식_지출_총금액       0
dtype: int64

In [166]:
df_소득소비['기준_년분기_코드'].unique()

array([20231, 20232, 20191, 20204, 20192, 20193, 20194, 20201, 20202,
       20203, 20211, 20212, 20213, 20214, 20221, 20222, 20223, 20224],
      dtype=int64)

In [32]:
# # 소득소비 merge
# df_total=pd.merge(df_total,df_소득소비,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])

In [33]:
# df_total.shape

(7650, 62)

In [167]:
# 아파트
dfs_아파트=[]
for f_name in glob(path+'아파트/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_아파트.append(temp)
df_아파트,=dfs_아파트

In [168]:
df_아파트.shape

(6368, 18)

In [169]:
df_아파트.isna().sum()

기준_년분기_코드                    0
행정동_코드                       0
행정동_코드_명                     0
아파트_단지_수                     0
아파트_면적_66_제곱미터_미만_세대_수      74
아파트_면적_66_제곱미터_세대_수          3
아파트_면적_99_제곱미터_세대_수        123
아파트_면적_132_제곱미터_세대_수      1126
아파트_면적_165_제곱미터_세대_수      2989
아파트_가격_1_억_미만_세대_수         563
아파트_가격_1_억_세대_수            298
아파트_가격_2_억_세대_수            241
아파트_가격_3_억_세대_수            248
아파트_가격_4_억_세대_수            682
아파트_가격_5_억_세대_수           1368
아파트_가격_6_억_이상_세대_수        2090
아파트_평균_면적                    0
아파트_평균_시가                    0
dtype: int64

In [170]:
df_아파트.fillna(0,inplace=True)

In [171]:
df_아파트.isna().sum()

기준_년분기_코드                 0
행정동_코드                    0
행정동_코드_명                  0
아파트_단지_수                  0
아파트_면적_66_제곱미터_미만_세대_수    0
아파트_면적_66_제곱미터_세대_수       0
아파트_면적_99_제곱미터_세대_수       0
아파트_면적_132_제곱미터_세대_수      0
아파트_면적_165_제곱미터_세대_수      0
아파트_가격_1_억_미만_세대_수        0
아파트_가격_1_억_세대_수           0
아파트_가격_2_억_세대_수           0
아파트_가격_3_억_세대_수           0
아파트_가격_4_억_세대_수           0
아파트_가격_5_억_세대_수           0
아파트_가격_6_억_이상_세대_수        0
아파트_평균_면적                 0
아파트_평균_시가                 0
dtype: int64

In [172]:
temp_=list(df_아파트['기준_년분기_코드'].unique())
sorted(temp_)


[20194,
 20201,
 20202,
 20203,
 20204,
 20211,
 20212,
 20213,
 20214,
 20221,
 20222,
 20223,
 20224,
 20231,
 20232]

In [38]:
# # 아파트 merge
# df_total=pd.merge(df_total,df_아파트,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])

In [173]:
# 영역
dfs_영역=[]
for f_name in glob(path+'영역/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_영역.append(temp)
df_영역,=dfs_영역

In [174]:
df_영역.shape

(425, 5)

In [175]:
# 점포
dfs_점포=[]
for f_name in glob(path+'점포/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_점포.append(temp)
e,f,g,h=dfs_점포

In [176]:
e.shape,f.shape,g.shape,h.shape

((139799, 12), (140538, 12), (141137, 12), (141334, 12))

In [177]:
columns_equal = all(e.columns == f.columns)
columns_equal

True

In [178]:
columns_equal = all(g.columns == h.columns)
columns_equal

True

In [179]:
e['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194], dtype=int64)

In [180]:
e_1=e.loc[e['기준_년분기_코드']==20191]
e_2=e.loc[e['기준_년분기_코드']==20192]
e_3=e.loc[e['기준_년분기_코드']==20193]
e_4=e.loc[e['기준_년분기_코드']==20194]

In [181]:
f['기준_년분기_코드'].unique()

array([20201, 20202, 20203, 20204], dtype=int64)

In [182]:
f_1=f.loc[f['기준_년분기_코드']==20201]
f_2=f.loc[f['기준_년분기_코드']==20202]
f_3=f.loc[f['기준_년분기_코드']==20203]
f_4=f.loc[f['기준_년분기_코드']==20204]

In [183]:
g['기준_년분기_코드'].unique()

array([20211, 20212, 20213, 20214], dtype=int64)

In [184]:
g_1=g.loc[g['기준_년분기_코드']==20211]
g_2=g.loc[g['기준_년분기_코드']==20212]
g_3=g.loc[g['기준_년분기_코드']==20213]
g_4=g.loc[g['기준_년분기_코드']==20214]

In [185]:
h['기준_년분기_코드'].unique()

array([20221, 20222, 20223, 20224], dtype=int64)

In [186]:
h_1=h.loc[h['기준_년분기_코드']==20221]
h_2=h.loc[h['기준_년분기_코드']==20222]
h_3=h.loc[h['기준_년분기_코드']==20223]
h_4=h.loc[h['기준_년분기_코드']==20224]

In [187]:
len(e_1['행정동_코드'].unique()),len(e_2['행정동_코드'].unique()),len(e_3['행정동_코드'].unique()),len(e_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [188]:
len(f_1['행정동_코드'].unique()),len(f_2['행정동_코드'].unique()),len(f_3['행정동_코드'].unique()),len(f_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [189]:
len(g_1['행정동_코드'].unique()),len(g_2['행정동_코드'].unique()),len(g_3['행정동_코드'].unique()),len(g_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [190]:
len(h_1['행정동_코드'].unique()),len(h_2['행정동_코드'].unique()),len(h_3['행정동_코드'].unique()),len(h_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [191]:
e_1.shape,e_2.shape,e_3.shape,e_4.shape

((34853, 12), (34925, 12), (34987, 12), (35034, 12))

In [192]:
df_점포=pd.concat([e,f,g,h],axis=0)
df_점포.shape

(562808, 12)

In [193]:
df_점포.isna().sum()

기준_년분기_코드      0
행정동_코드         0
행정동_코드_명       0
서비스_업종_코드      0
서비스_업종_코드_명    0
점포_수           0
유사_업종_점포_수     0
개업_율           0
개업_점포_수        0
폐업_률           0
폐업_점포_수        0
프랜차이즈_점포_수     0
dtype: int64

In [199]:
# 직장인구
dfs_직장인구=[]
for f_name in glob(path+'직장인구/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_직장인구.append(temp)
df_직장인구,=dfs_직장인구

In [200]:
df_직장인구.shape

(7636, 24)

In [201]:
df_직장인구.isna().sum()

기준_년분기_코드              0
행정동_코드                 0
행정동_코드_명               0
총_직장_인구_수              0
남성_직장_인구_수             0
여성_직장_인구_수             0
연령대_10_직장_인구_수         0
연령대_20_직장_인구_수         0
연령대_30_직장_인구_수         0
연령대_40_직장_인구_수         0
연령대_50_직장_인구_수         0
연령대_60_이상_직장_인구_수      0
남성연령대_10_직장_인구_수       0
남성연령대_20_직장_인구_수       0
남성연령대_30_직장_인구_수       0
남성연령대_40_직장_인구_수       0
남성연령대_50_직장_인구_수       0
남성연령대_60_이상_직장_인구_수    0
여성연령대_10_직장_인구_수       0
여성연령대_20_직장_인구_수       0
여성연령대_30_직장_인구_수       0
여성연령대_40_직장_인구_수       0
여성연령대_50_직장_인구_수       0
여성연령대_60_이상_직장_인구_수    0
dtype: int64

In [202]:
temp_total=0
cnt=0
for x in df_직장인구['기준_년분기_코드'].unique():
    print("년분기:",x,end='  ')
    print(df_직장인구.loc[df_직장인구['기준_년분기_코드']==x]['기준_년분기_코드'].count(),end='  ')
    if cnt%7==0:
        print()
    cnt+=1
print("cnt:",cnt)

년분기: 20191  425  
년분기: 20192  418  년분기: 20193  418  년분기: 20194  425  년분기: 20201  425  년분기: 20202  425  년분기: 20203  425  년분기: 20211  425  
년분기: 20212  425  년분기: 20213  425  년분기: 20221  425  년분기: 20222  425  년분기: 20223  425  년분기: 20231  425  년분기: 20232  425  
년분기: 20224  425  년분기: 20204  425  년분기: 20214  425  cnt: 18


In [203]:
dong_code_직장_20192=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20192]['행정동_코드'])
diff_직장_192=[x for x in dong_code_20194 if x not in dong_code_직장_20192 ]

In [204]:
dong_code_직장_20193=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20193]['행정동_코드'])
diff_직장_193=[x for x in dong_code_20194 if x not in dong_code_직장_20193 ]

In [216]:
# 19년 2,3분기 7개 동 데이터 없음 -> 19년 1분기 7개 동 데이터로 채워넣음
for x in diff_직장_192:
    new_row1=df_직장인구.loc[(df_직장인구['행정동_코드']==x)&(df_직장인구['기준_년분기_코드']==20191)]
    new_row1['기준_년분기_코드']=20192
    new_row2=df_직장인구.loc[(df_직장인구['행정동_코드']==x)&(df_직장인구['기준_년분기_코드']==20191)]
    new_row2['기준_년분기_코드']=20193
    df_직장인구.append(new_row1)
    df_직장인구.append(new_row2)
    

     기준_년분기_코드    행정동_코드 행정동_코드_명  총_직장_인구_수  남성_직장_인구_수  여성_직장_인구_수  \
123      20191  11305595      번1동       4381        2302        2079   

     연령대_10_직장_인구_수  연령대_20_직장_인구_수  연령대_30_직장_인구_수  연령대_40_직장_인구_수  ...  \
123              13             571             865             963  ...   

     남성연령대_30_직장_인구_수  남성연령대_40_직장_인구_수  남성연령대_50_직장_인구_수  \
123               500               510               642   

     남성연령대_60_이상_직장_인구_수  여성연령대_10_직장_인구_수  여성연령대_20_직장_인구_수  \
123                  440                 7               367   

     여성연령대_30_직장_인구_수  여성연령대_40_직장_인구_수  여성연령대_50_직장_인구_수  여성연령대_60_이상_직장_인구_수  
123               365               453               515                  372  

[1 rows x 24 columns]
     기준_년분기_코드    행정동_코드 행정동_코드_명  총_직장_인구_수  남성_직장_인구_수  여성_직장_인구_수  \
181      20191  11305603      번2동       2150        1295         855   

     연령대_10_직장_인구_수  연령대_20_직장_인구_수  연령대_30_직장_인구_수  연령대_40_직장_인구_수  ...  \
181               5             209         

In [205]:
diff_직장_192,diff_직장_193
# 번1,2,3동/ 수유1,2,3동/ 항동

([11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800],
 [11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800])

In [ ]:
for new in diff_직장_192:
    new_rows=pd.DataFrame({'기준_년분기_코드':,'행정동_코드'})

In [209]:
temp_직장인구=df_직장인구.loc[df_직장인구['기준_년분기_코드']==20191]
temp_직장인구=temp_직장인구.loc[temp_직장인구['행정동_코드']==11305595]
temp_직장인구


기준_년분기_코드    행정동_코드 행정동_코드_명  총_직장_인구_수  남성_직장_인구_수  여성_직장_인구_수  \
123      20191  11305595      번1동       4381        2302        2079   

     연령대_10_직장_인구_수  연령대_20_직장_인구_수  연령대_30_직장_인구_수  연령대_40_직장_인구_수  ...  \
123              13             571             865             963  ...   

     남성연령대_30_직장_인구_수  남성연령대_40_직장_인구_수  남성연령대_50_직장_인구_수  \
123               500               510               642   

     남성연령대_60_이상_직장_인구_수  여성연령대_10_직장_인구_수  여성연령대_20_직장_인구_수  \
123                  440                 7               367   

     여성연령대_30_직장_인구_수  여성연령대_40_직장_인구_수  여성연령대_50_직장_인구_수  여성연령대_60_이상_직장_인구_수  
123               365               453               515                  372  

[1 rows x 24 columns]

In [214]:
temp1=df_직장인구.loc[df_직장인구['기준_년분기_코드']==20192]
temp1.loc[temp1['행정동_코드']==11305595]

Empty DataFrame
Columns: [기준_년분기_코드, 행정동_코드, 행정동_코드_명, 총_직장_인구_수, 남성_직장_인구_수, 여성_직장_인구_수, 연령대_10_직장_인구_수, 연령대_20_직장_인구_수, 연령대_30_직장_인구_수, 연령대_40_직장_인구_수, 연령대_50_직장_인구_수, 연령대_60_이상_직장_인구_수, 남성연령대_10_직장_인구_수, 남성연령대_20_직장_인구_수, 남성연령대_30_직장_인구_수, 남성연령대_40_직장_인구_수, 남성연령대_50_직장_인구_수, 남성연령대_60_이상_직장_인구_수, 여성연령대_10_직장_인구_수, 여성연령대_20_직장_인구_수, 여성연령대_30_직장_인구_수, 여성연령대_40_직장_인구_수, 여성연령대_50_직장_인구_수, 여성연령대_60_이상_직장_인구_수]
Index: []

[0 rows x 24 columns]

In [71]:
# # 직장인구 merge
# df_total=pd.merge(df_total,df_직장인구,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])
# df_total.shape

(7650, 98)

In [213]:
# 집객시설
dfs_집객시설=[]
for f_name in glob(path+'집객시설/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_집객시설.append(temp)
df_집객시설,=dfs_집객시설
df_집객시설.shape

(4675, 23)

In [74]:
temp_total=0
cnt=0
for x in df_집객시설['기준_년분기_코드'].unique():
    print("년분기:",x,end='  ')
    print(df_집객시설.loc[df_집객시설['기준_년분기_코드']==x]['기준_년분기_코드'].count(),end='  ')
    if cnt%7==0:
        print()
    cnt+=1
print("cnt:",cnt)

년분기: 20232  425  
년분기: 20231  425  년분기: 20204  425  년분기: 20214  425  년분기: 20211  425  년분기: 20212  425  년분기: 20221  425  년분기: 20222  425  
년분기: 20213  425  년분기: 20223  425  년분기: 20224  425  cnt: 11


In [75]:
# 집객시설 merge
df_total=pd.merge(df_total,df_집객시설,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])
df_total.shape

(7650, 118)

In [76]:
# 추정매출
dfs_추정매출=[]
for f_name in glob(path+'추정매출/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_추정매출.append(temp)
i,j,k,l=dfs_추정매출

In [77]:
i.shape,j.shape,k.shape,l.shape

((65758, 53), (66583, 53), (67111, 53), (67748, 53))

In [81]:
columns_equal = all(i.columns == j.columns)
columns_equal


True

In [82]:
columns_equal = all(k.columns == l.columns)
columns_equal

True

In [85]:
i['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194], dtype=int64)

In [86]:
i_1=i.loc[i['기준_년분기_코드']==20191]
i_2=i.loc[i['기준_년분기_코드']==20192]
i_3=i.loc[i['기준_년분기_코드']==20193]
i_4=i.loc[i['기준_년분기_코드']==20194]

In [87]:
j['기준_년분기_코드'].unique()

array([20201, 20202, 20203, 20204], dtype=int64)

In [88]:
j_1=j.loc[j['기준_년분기_코드']==20201]
j_2=j.loc[j['기준_년분기_코드']==20202]
j_3=j.loc[j['기준_년분기_코드']==20203]
j_4=j.loc[j['기준_년분기_코드']==20204]

In [89]:
k['기준_년분기_코드'].unique()

array([20211, 20212, 20213, 20214], dtype=int64)

In [90]:
k_1=k.loc[k['기준_년분기_코드']==20211]
k_2=k.loc[k['기준_년분기_코드']==20212]
k_3=k.loc[k['기준_년분기_코드']==20213]
k_4=k.loc[k['기준_년분기_코드']==20214]

In [91]:
l['기준_년분기_코드'].unique()

array([20221, 20222, 20223, 20224], dtype=int64)

In [92]:
l_1=l.loc[l['기준_년분기_코드']==20221]
l_2=l.loc[l['기준_년분기_코드']==20222]
l_3=l.loc[l['기준_년분기_코드']==20223]
l_4=l.loc[l['기준_년분기_코드']==20224]

In [140]:
dong_code_추정매출_191=list(i_1.loc[i_1['기준_년분기_코드']==20191]['행정동_코드'])
dong_code_추정매출_192=list(i_2.loc[i_2['기준_년분기_코드']==20192]['행정동_코드'])
dong_code_추정매출_193=list(i_3.loc[i_3['기준_년분기_코드']==20193]['행정동_코드'])
dong_code_추정매출_194=list(i_4.loc[i_4['기준_년분기_코드']==20194]['행정동_코드'])

In [141]:
diff_추정매출_191=[x for x in dong_code_20194 if x not in dong_code_추정매출_191 ]
diff_추정매출_192=[x for x in dong_code_20194 if x not in dong_code_추정매출_192 ]
diff_추정매출_193=[x for x in dong_code_20194 if x not in dong_code_추정매출_193 ]
diff_추정매출_194=[x for x in dong_code_20194 if x not in dong_code_추정매출_194 ]

In [142]:
diff_추정매출_191,diff_추정매출_192,diff_추정매출_193,diff_추정매출_194

([11530800, 11740690],
 [11530800, 11740690],
 [11530800, 11740690],
 [11530800, 11740690])

In [124]:
dong_code_추정매출_201=list(j_1.loc[j_1['기준_년분기_코드']==20201]['행정동_코드'])
dong_code_추정매출_202=list(j_2.loc[j_2['기준_년분기_코드']==20202]['행정동_코드'])
dong_code_추정매출_203=list(j_3.loc[j_3['기준_년분기_코드']==20203]['행정동_코드'])
dong_code_추정매출_204=list(j_4.loc[j_4['기준_년분기_코드']==20204]['행정동_코드'])

In [125]:
diff_추정매출_201=[x for x in dong_code_20194 if x not in dong_code_추정매출_201 ]
diff_추정매출_202=[x for x in dong_code_20194 if x not in dong_code_추정매출_202 ]
diff_추정매출_203=[x for x in dong_code_20194 if x not in dong_code_추정매출_203 ]
diff_추정매출_204=[x for x in dong_code_20194 if x not in dong_code_추정매출_204 ]

In [127]:
diff_추정매출_201,diff_추정매출_202,diff_추정매출_203,diff_추정매출_204

([11530800, 11740690],
 [11530800, 11740690],
 [11530800, 11740690],
 [11530800, 11740690])

In [ ]:
# 항동:     11530800
# 둔촌1동:  11740690


In [132]:
dong_code_추정매출_211=list(k_1.loc[k_1['기준_년분기_코드']==20211]['행정동_코드'])
dong_code_추정매출_212=list(k_2.loc[k_2['기준_년분기_코드']==20212]['행정동_코드'])
dong_code_추정매출_213=list(k_3.loc[k_3['기준_년분기_코드']==20213]['행정동_코드'])
dong_code_추정매출_214=list(k_4.loc[k_4['기준_년분기_코드']==20214]['행정동_코드'])

In [133]:
diff_추정매출_211=[x for x in dong_code_20194 if x not in dong_code_추정매출_211 ]
diff_추정매출_212=[x for x in dong_code_20194 if x not in dong_code_추정매출_212 ]
diff_추정매출_213=[x for x in dong_code_20194 if x not in dong_code_추정매출_213 ]
diff_추정매출_214=[x for x in dong_code_20194 if x not in dong_code_추정매출_214 ]

In [134]:
diff_추정매출_211,diff_추정매출_212,diff_추정매출_213,diff_추정매출_214

([11530800, 11740690],
 [11530800, 11740690],
 [11530800, 11740690],
 [11530800, 11740690])

In [135]:
dong_code_추정매출_221=list(l_1.loc[l_1['기준_년분기_코드']==20221]['행정동_코드'])
dong_code_추정매출_222=list(l_2.loc[l_2['기준_년분기_코드']==20222]['행정동_코드'])
dong_code_추정매출_223=list(l_3.loc[l_3['기준_년분기_코드']==20223]['행정동_코드'])
dong_code_추정매출_224=list(l_4.loc[l_4['기준_년분기_코드']==20224]['행정동_코드'])

In [136]:
diff_추정매출_221=[x for x in dong_code_20194 if x not in dong_code_추정매출_221 ]
diff_추정매출_222=[x for x in dong_code_20194 if x not in dong_code_추정매출_222 ]
diff_추정매출_223=[x for x in dong_code_20194 if x not in dong_code_추정매출_223 ]
diff_추정매출_224=[x for x in dong_code_20194 if x not in dong_code_추정매출_224 ]

In [137]:
diff_추정매출_221,diff_추정매출_222,diff_추정매출_223,diff_추정매출_224

([11530800, 11740690], [11740690], [11740690], [11740690])

In [93]:
len(i_1['행정동_코드'].unique()),len(i_2['행정동_코드'].unique()),len(i_3['행정동_코드'].unique()),len(i_4['행정동_코드'].unique())

(423, 423, 423, 423)

In [94]:
len(j_1['행정동_코드'].unique()),len(j_2['행정동_코드'].unique()),len(j_3['행정동_코드'].unique()),len(j_4['행정동_코드'].unique())

(423, 423, 423, 423)

In [95]:
len(k_1['행정동_코드'].unique()),len(k_2['행정동_코드'].unique()),len(k_3['행정동_코드'].unique()),len(k_4['행정동_코드'].unique())

(423, 423, 423, 423)

In [96]:
len(l_1['행정동_코드'].unique()),len(l_2['행정동_코드'].unique()),len(l_3['행정동_코드'].unique()),len(l_4['행정동_코드'].unique())

(423, 424, 424, 424)

In [97]:
i_1.shape,i_2.shape,i_3.shape,i_4.shape,j_1.shape,j_2.shape,j_3.shape,j_4.shape,k_1.shape,k_2.shape,k_3.shape,k_4.shape,l_1.shape,l_2.shape,l_3.shape,l_4.shape

((16298, 53),
 (16436, 53),
 (16471, 53),
 (16553, 53),
 (16525, 53),
 (16678, 53),
 (16695, 53),
 (16685, 53),
 (16640, 53),
 (16798, 53),
 (16806, 53),
 (16867, 53),
 (16830, 53),
 (16934, 53),
 (16976, 53),
 (17008, 53))

In [103]:
# 추정매출 합치기
df_추정매출=pd.concat([i,j,k,l],axis=0)
df_추정매출.shape


(267200, 53)

In [122]:
# merge (outer join)
df_total_2=pd.merge(df_total_2,df_추정매출,how='outer',on=['기준_년분기_코드', '행정동_코드', '행정동_코드_명', '서비스_업종_코드', '서비스_업종_코드_명'])
df_total_2.shape

(562808, 60)

In [119]:
df_total.shape,df_total_2.shape

((7650, 118), (562808, 60))

In [212]:
df_집객시설

Empty DataFrame
Columns: []
Index: []