In [ ]:

# 행정동 데이터 전처리요~


In [2]:
import numpy as np
import pandas as pd
import os
from glob import glob


In [4]:


df_total=pd.DataFrame()

df_거주인구=pd.DataFrame()
df_상주인구=pd.DataFrame()
df_생활인구=pd.DataFrame()
df_소득소비=pd.DataFrame()
df_아파트=pd.DataFrame()
df_영역=pd.DataFrame()
df_점포=pd.DataFrame()
df_직장인구=pd.DataFrame()
df_집객시설=pd.DataFrame()
df_추정매출=pd.DataFrame()
df_학교=pd.DataFrame()



In [5]:
path='C:/Users/user/big_proj/data/raw data/행정동/'


In [6]:
# 거주인구
dfs_거주인구=[]
for f_name in glob(path+'거주인구/*.csv'):
    temp=pd.read_csv(f_name)
    dfs_거주인구.append(temp)
    # df_거주인구=pd.concat([df_거주인구,temp],)
a,b,c,d=dfs_거주인구

print(a.shape,b.shape,c.shape,d.shape)


(452, 15) (453, 15) (454, 15) (454, 15)


In [22]:
a.isna().sum()

동별(1)      0
동별(2)      0
동별(3)      0
2019       0
2019.1     0
2019.2     0
2019.3     0
2019.4     0
2019.5     0
2019.6     0
2019.7     0
2019.8     0
2019.9     0
2019.10    0
2019.11    0
dtype: int64

In [23]:
b.isna().sum()

동별(1)      0
동별(2)      0
동별(3)      0
2020       0
2020.1     0
2020.2     0
2020.3     0
2020.4     0
2020.5     0
2020.6     0
2020.7     0
2020.8     0
2020.9     0
2020.10    0
2020.11    0
dtype: int64

In [24]:
c.isna().sum()

동별(1)      0
동별(2)      0
동별(3)      0
2021       0
2021.1     0
2021.2     0
2021.3     0
2021.4     0
2021.5     0
2021.6     0
2021.7     0
2021.8     0
2021.9     0
2021.10    0
2021.11    0
dtype: int64

In [25]:
d.isna().sum()

동별(1)      0
동별(2)      0
동별(3)      0
2022       0
2022.1     0
2022.2     0
2022.3     0
2022.4     0
2022.5     0
2022.6     0
2022.7     0
2022.8     0
2022.9     0
2022.10    0
2022.11    0
dtype: int64

In [8]:
# 상주인구
dfs_상주인구=[]
for f_name in glob(path+'상주인구/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_상주인구.append(temp)
df_상주인구,=dfs_상주인구

df_상주인구.head()

기준_년분기_코드    행정동_코드 행정동_코드_명  총_상주인구_수  남성_상주인구_수  여성_상주인구_수  \
0      20191  11110515    청운효자동     13047       6111       6936   
1      20191  11110530      사직동      9224       4169       5055   
2      20191  11110540      삼청동      2831       1344       1487   
3      20191  11110550      부암동     10055       4850       5205   
4      20191  11110560      평창동     18615       8775       9840   

   연령대_10_상주인구_수  연령대_20_상주인구_수  연령대_30_상주인구_수  연령대_40_상주인구_수  ...  \
0           2248           1648           1879           2304  ...   
1           1387           1095           1383           1558  ...   
2            340            336            422            399  ...   
3           1490           1394           1277           1647  ...   
4           3018           2691           2303           2848  ...   

   남성연령대_60_이상_상주인구_수  여성연령대_10_상주인구_수  여성연령대_20_상주인구_수  여성연령대_30_상주인구_수  \
0                1235             1052              821             1020   
1                1021              697              603              781   
2                 383              156              171              220   
3                1137              689              633              672   
4                1976             1472             1272             1231   

   여성연령대_40_상주인구_수  여성연령대_50_상주인구_수  여성연령대_60_이상_상주인구_수  총_가구_수  아파트_가구_수  \
0             1283             1062                1698    5384       314   
1              856              810                1308    4352       163   
2              201              253                 486    1413         0   
3              905              909                1397    4243        74   
4             1592             1757                2516    7463       459   

   비_아파트_가구_수  
0        5070  
1        4189  
2        1413  
3        4169  
4        7004  

[5 rows x 27 columns]

In [9]:
df_상주인구.shape

(7629, 27)

In [10]:
df_상주인구.dtypes

기준_년분기_코드              int64
행정동_코드                 int64
행정동_코드_명              object
총_상주인구_수               int64
남성_상주인구_수              int64
여성_상주인구_수              int64
연령대_10_상주인구_수          int64
연령대_20_상주인구_수          int64
연령대_30_상주인구_수          int64
연령대_40_상주인구_수          int64
연령대_50_상주인구_수          int64
연령대_60_이상_상주인구_수       int64
남성연령대_10_상주인구_수        int64
남성연령대_20_상주인구_수        int64
남성연령대_30_상주인구_수        int64
남성연령대_40_상주인구_수        int64
남성연령대_50_상주인구_수        int64
남성연령대_60_이상_상주인구_수     int64
여성연령대_10_상주인구_수        int64
여성연령대_20_상주인구_수        int64
여성연령대_30_상주인구_수        int64
여성연령대_40_상주인구_수        int64
여성연령대_50_상주인구_수        int64
여성연령대_60_이상_상주인구_수     int64
총_가구_수                 int64
아파트_가구_수               int64
비_아파트_가구_수             int64
dtype: object

In [11]:
temp=df_상주인구.loc[df_상주인구['행정동_코드']==11110515]
temp

기준_년분기_코드    행정동_코드 행정동_코드_명  총_상주인구_수  남성_상주인구_수  여성_상주인구_수  \
0         20191  11110515    청운효자동     13047       6111       6936   
418       20192  11110515    청운효자동     13030       6109       6921   
836       20193  11110515    청운효자동     13030       6109       6921   
1254      20194  11110515    청운효자동     12817       5963       6854   
1679      20201  11110515    청운효자동     12817       5963       6854   
2239      20202  11110515    청운효자동     12817       5963       6854   
2529      20203  11110515    청운효자동     12817       5963       6854   
2954      20204  11110515    청운효자동     12434       5780       6654   
3379      20211  11110515    청운효자동     12434       5780       6654   
3533      20212  11110515    청운효자동     12434       5780       6654   
3958      20213  11110515    청운효자동     12434       5780       6654   
4060      20214  11110515    청운효자동     12434       5780       6654   
4485      20221  11110515    청운효자동     12434       5780       6654   
4910      20222  11110515    청운효자동     12434       5780       6654   
5335      20224  11110515    청운효자동     13009       6104       6905   
6179      20232  11110515    청운효자동     13009       6104       6905   
6583      20231  11110515    청운효자동     13009       6104       6905   
6603      20223  11110515    청운효자동     12434       5780       6654   

      연령대_10_상주인구_수  연령대_20_상주인구_수  연령대_30_상주인구_수  연령대_40_상주인구_수  ...  \
0              2248           1648           1879           2304  ...   
418            2288           1641           1883           2314  ...   
836            2288           1641           1883           2314  ...   
1254           2171           1630           1765           2276  ...   
1679           2171           1630           1765           2276  ...   
2239           2171           1630           1765           2276  ...   
2529           2171           1630           1765           2276  ...   
2954           1993           1594           1697           2148  ...   
3379           1993           1594           1697           2148  ...   
3533           1993           1594           1697           2148  ...   
3958           1993           1594           1697           2148  ...   
4060           1993           1594           1697           2148  ...   
4485           1993           1594           1697           2148  ...   
4910           1993           1594           1697           2148  ...   
5335           1650           1622           1661           2151  ...   
6179           1650           1622           1661           2151  ...   
6583           1650           1622           1661           2151  ...   
6603           1993           1594           1697           2148  ...   

      남성연령대_60_이상_상주인구_수  여성연령대_10_상주인구_수  여성연령대_20_상주인구_수  여성연령대_30_상주인구_수  \
0                   1235             1052              821             1020   
418                 1228             1070              812             1023   
836                 1228             1070              812             1023   
1254                1259             1035              836              946   
1679                1259             1035              836              946   
2239                1259             1035              836              946   
2529                1259             1035              836              946   
2954                1275              947              801              917   
3379                1275              947              801              917   
3533                1275              947              801              917   
3958                1275              947              801              917   
4060                1275              947              801              917   
4485                1275              947              801              917   
4910                1275              947              801              917   
5335                1608              783              778              877   
6179                160

In [12]:
df_상주인구['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194, 20201, 20202, 20203, 20204, 20211,
       20212, 20213, 20214, 20221, 20222, 20224, 20231, 20232, 20223],
      dtype=int64)

In [19]:
df_상주인구.isna().sum()

기준_년분기_코드             0
행정동_코드                0
행정동_코드_명              0
총_상주인구_수              0
남성_상주인구_수             0
여성_상주인구_수             0
연령대_10_상주인구_수         0
연령대_20_상주인구_수         0
연령대_30_상주인구_수         0
연령대_40_상주인구_수         0
연령대_50_상주인구_수         0
연령대_60_이상_상주인구_수      0
남성연령대_10_상주인구_수       0
남성연령대_20_상주인구_수       0
남성연령대_30_상주인구_수       0
남성연령대_40_상주인구_수       0
남성연령대_50_상주인구_수       0
남성연령대_60_이상_상주인구_수    0
여성연령대_10_상주인구_수       0
여성연령대_20_상주인구_수       0
여성연령대_30_상주인구_수       0
여성연령대_40_상주인구_수       0
여성연령대_50_상주인구_수       0
여성연령대_60_이상_상주인구_수    0
총_가구_수                0
아파트_가구_수              0
비_아파트_가구_수            0
dtype: int64

In [13]:
df_total=df_상주인구.copy()
df_total.shape

(7629, 27)

In [17]:
# 생활인구
dfs_생활인구=[]
for f_name in glob(path+'생활인구/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_생활인구.append(temp)
df_생활인구,=dfs_생활인구


In [18]:
df_생활인구.shape

(7650, 25)

In [26]:
df_생활인구['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194, 20201, 20202, 20203, 20204, 20211,
       20212, 20213, 20214, 20221, 20222, 20223, 20224, 20231, 20232],
      dtype=int64)

In [29]:
df_생활인구.isna().sum()

기준_년분기_코드           0
행정동_코드              0
행정동_코드_명            0
총_유동인구_수            0
남성_유동인구_수           0
여성_유동인구_수           0
연령대_10_유동인구_수       0
연령대_20_유동인구_수       0
연령대_30_유동인구_수       0
연령대_40_유동인구_수       0
연령대_50_유동인구_수       0
연령대_60_이상_유동인구_수    0
시간대_00_06_유동인구_수    0
시간대_06_11_유동인구_수    0
시간대_11_14_유동인구_수    0
시간대_14_17_유동인구_수    0
시간대_17_21_유동인구_수    0
시간대_21_24_유동인구_수    0
월요일_유동인구_수          0
화요일_유동인구_수          0
수요일_유동인구_수          0
목요일_유동인구_수          0
금요일_유동인구_수          0
토요일_유동인구_수          0
일요일_유동인구_수          0
dtype: int64

In [ ]:
temp=df_생활인구.loc[df_생활인구['행정동_코드']==11110515]
temp

In [35]:
pd.set_option('display.max_rows', 30)

In [38]:
temp_total=0
cnt=0
for x in df_생활인구['기준_년분기_코드'].unique():
    print("년분기:",x,end='  ')
    print(df_생활인구.loc[df_생활인구['기준_년분기_코드']==x]['기준_년분기_코드'].count(),end='  ')
    if cnt%7==0:
        print()
    cnt+=1
print("cnt:",cnt)

년분기: 20191  425  
년분기: 20192  425  년분기: 20193  425  년분기: 20194  425  년분기: 20201  425  년분기: 20202  425  년분기: 20203  425  년분기: 20204  425  
년분기: 20211  425  년분기: 20212  425  년분기: 20213  425  년분기: 20214  425  년분기: 20221  425  년분기: 20222  425  년분기: 20223  425  
년분기: 20224  425  년분기: 20231  425  년분기: 20232  425  cnt: 18


In [40]:
temp_total=0
cnt=0
for x in df_상주인구['기준_년분기_코드'].unique():
    print("년분기:",x,end='  ')
    print(df_상주인구.loc[df_상주인구['기준_년분기_코드']==x]['기준_년분기_코드'].count(),end='  ')
    if cnt%7==0:
        print()
    cnt+=1
print("cnt:",cnt)

년분기: 20191  418  
년분기: 20192  418  년분기: 20193  418  년분기: 20194  425  년분기: 20201  425  년분기: 20202  425  년분기: 20203  425  년분기: 20204  425  
년분기: 20211  425  년분기: 20212  425  년분기: 20213  425  년분기: 20214  425  년분기: 20221  425  년분기: 20222  425  년분기: 20224  425  
년분기: 20231  425  년분기: 20232  425  년분기: 20223  425  cnt: 18


In [56]:
# 20191, 20192, 20193
dong_code_20191=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20191]['행정동_코드'])
dong_code_20192=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20192]['행정동_코드'])
dong_code_20193=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20193]['행정동_코드'])
dong_code_20194=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20194]['행정동_코드'])

In [75]:
diff_191=[x for x in dong_code_20194 if x not in dong_code_20191 ]
diff_192=[x for x in dong_code_20194 if x not in dong_code_20192 ]
diff_193=[x for x in dong_code_20194 if x not in dong_code_20193 ]
print(diff_191)
print(diff_192)
print(diff_193)
# 번1,2,3동, 수유1,2,3동, 항동

[11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800]
[11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800]
[11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800]


In [80]:
# 생활인구 merge
df_total=pd.merge(df_생활인구,df_total,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])

In [83]:
df_total.shape

(7650, 49)

In [84]:
# 소득소비
dfs_소득소비=[]
for f_name in glob(path+'소득소비/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_소득소비.append(temp)
df_소득소비,=dfs_소득소비

In [86]:
df_소득소비.shape

(7650, 16)

In [87]:
df_소득소비.isna().sum()

기준_년분기_코드       0
행정동_코드          0
행정동_코드_명        0
월_평균_소득_금액      0
소득_구간_코드        0
지출_총금액          0
식료품_지출_총금액      0
의류_신발_지출_총금액    0
생활용품_지출_총금액     0
의료비_지출_총금액      0
교통_지출_총금액       0
교육_지출_총금액       0
유흥_지출_총금액       0
여가_문화_지출_총금액    0
기타_지출_총금액       0
음식_지출_총금액       0
dtype: int64

In [90]:
# 소득소비 merge
df_total=pd.merge(df_total,df_소득소비,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])

In [91]:
df_total.shape

(7650, 62)

In [92]:
# 아파트
dfs_아파트=[]
for f_name in glob(path+'아파트/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_아파트.append(temp)
df_아파트,=dfs_아파트

In [93]:
df_아파트.shape

(6368, 18)

In [104]:
df_아파트.isna().sum()

기준_년분기_코드                    0
행정동_코드                       0
행정동_코드_명                     0
아파트_단지_수                     0
아파트_면적_66_제곱미터_미만_세대_수      74
아파트_면적_66_제곱미터_세대_수          3
아파트_면적_99_제곱미터_세대_수        123
아파트_면적_132_제곱미터_세대_수      1126
아파트_면적_165_제곱미터_세대_수      2989
아파트_가격_1_억_미만_세대_수         563
아파트_가격_1_억_세대_수            298
아파트_가격_2_억_세대_수            241
아파트_가격_3_억_세대_수            248
아파트_가격_4_억_세대_수            682
아파트_가격_5_억_세대_수           1368
아파트_가격_6_억_이상_세대_수        2090
아파트_평균_면적                    0
아파트_평균_시가                    0
dtype: int64

In [101]:
temp_=list(df_아파트['기준_년분기_코드'].unique())
sorted(temp_)


[20194,
 20201,
 20202,
 20203,
 20204,
 20211,
 20212,
 20213,
 20214,
 20221,
 20222,
 20223,
 20224,
 20231,
 20232]

In [102]:
# 아파트 merge ????
df_temp=pd.merge(df_total,df_아파트,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])

In [103]:
df_temp.shape

(7650, 77)

In [106]:
# 영역
dfs_영역=[]
for f_name in glob(path+'영역/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_영역.append(temp)
df_영역,=dfs_영역

In [107]:
df_영역.shape

(425, 5)

In [111]:
df_영역

행정동_코드  행정동_명  엑스좌표_값  와이좌표_값    영역_면적
0    11110515  청운효자동  197342  453874  2568432
1    11110530    사직동  197383  452705  1158536
2    11110540    삼청동  198340  454312  1479255
3    11110550    부암동  196781  455266  2274739
4    11110560    평창동  197186  457344  8947328
..        ...    ...     ...     ...      ...
420  11740700   둔촌2동  213015  447989  1550455
421  11740640   성내1동  211097  447696   663675
422  11740650   성내2동  211287  448330   625147
423  11740660   성내3동  211824  447659   647356
424  11740685     길동  212900  448920  1631616

[425 rows x 5 columns]

In [113]:
# 점포
dfs_점포=[]
for f_name in glob(path+'점포/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_점포.append(temp)
e,f,g,h=dfs_점포

In [114]:
e.shape,f.shape,g.shape,h.shape

((139799, 12), (140538, 12), (141137, 12), (141334, 12))

In [124]:
e.columns,f.columns,g.columns,h.columns

(Index(['기준_년분기_코드', '행정동_코드', '행정동_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '점포_수',
        '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
       dtype='object'),
 Index(['기준_년분기_코드', '행정동_코드', '행정동_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '점포_수',
        '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
       dtype='object'),
 Index(['기준_년분기_코드', '행정동_코드', '행정동_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '점포_수',
        '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
       dtype='object'),
 Index(['기준_년분기_코드', '행정동_코드', '행정동_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '점포_수',
        '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
       dtype='object'))

In [163]:
e['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194], dtype=int64)

In [165]:
e_1=e.loc[e['기준_년분기_코드']==20191]
e_2=e.loc[e['기준_년분기_코드']==20192]
e_3=e.loc[e['기준_년분기_코드']==20193]
e_4=e.loc[e['기준_년분기_코드']==20194]

In [164]:
f['기준_년분기_코드'].unique()

array([20201, 20202, 20203, 20204], dtype=int64)

In [166]:
f_1=f.loc[f['기준_년분기_코드']==20201]
f_2=f.loc[f['기준_년분기_코드']==20202]
f_3=f.loc[f['기준_년분기_코드']==20203]
f_4=f.loc[f['기준_년분기_코드']==20204]

In [167]:
g['기준_년분기_코드'].unique()

array([20211, 20212, 20213, 20214], dtype=int64)

In [168]:
g_1=g.loc[g['기준_년분기_코드']==20211]
g_2=g.loc[g['기준_년분기_코드']==20212]
g_3=g.loc[g['기준_년분기_코드']==20213]
g_4=g.loc[g['기준_년분기_코드']==20214]

In [169]:
h['기준_년분기_코드'].unique()

array([20221, 20222, 20223, 20224], dtype=int64)

In [170]:
h_1=h.loc[h['기준_년분기_코드']==20221]
h_2=h.loc[h['기준_년분기_코드']==20222]
h_3=h.loc[h['기준_년분기_코드']==20223]
h_4=h.loc[h['기준_년분기_코드']==20224]

In [172]:
len(e_1['행정동_코드'].unique()),len(e_2['행정동_코드'].unique()),len(e_3['행정동_코드'].unique()),len(e_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [173]:
len(f_1['행정동_코드'].unique()),len(f_2['행정동_코드'].unique()),len(f_3['행정동_코드'].unique()),len(f_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [174]:
len(g_1['행정동_코드'].unique()),len(g_2['행정동_코드'].unique()),len(g_3['행정동_코드'].unique()),len(g_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [175]:
len(h_1['행정동_코드'].unique()),len(h_2['행정동_코드'].unique()),len(h_3['행정동_코드'].unique()),len(h_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [181]:
e_1.shape,e_2.shape,e_3.shape,e_4.shape

((34853, 12), (34925, 12), (34987, 12), (35034, 12))

In [152]:
# max_=0
# for x in dong_code_e:
#     temp=len(e.loc[e['행정동_코드']==x]['서비스_업종_코드'].unique())
#     print(temp)
#     if temp>max_:
#         max_=temp
#         max_dongcode=x
# print("max:",max_)
# print("max_dongcode:",max_dongcode)

81
93
64
73
75
55
72
70
96
85
80
86
78
67
55
73
84
85
88
88
88
74
92
91
85
87
77
76
85
77
86
81
80
72
94
86
88
79
62
72
94
77
59
85
76
92
66
81
73
91
84
77
88
72
63
80
75
77
84
88
92
89
96
79
93
93
82
85
88
84
82
82
87
90
85
84
92
91
85
93
97
94
91
74
85
82
95
88
92
79
81
75
82
75
85
72
78
87
82
89
82
92
77
83
85
79
92
78
83
79
86
93
89
69
73
83
85
76
78
70
80
83
82
85
84
89
77
78
75
86
76
93
90
86
74
90
67
72
84
85
89
75
83
83
81
73
87
89
86
87
76
91
81
72
87
76
74
88
69
77
94
88
76
60
78
72
78
76
85
91
81
84
82
67
65
70
89
83
86
84
88
78
92
91
76
85
86
88
72
81
74
89
77
77
89
93
92
89
84
73
79
89
80
85
74
83
84
94
90
90
93
79
85
93
99
92
83
85
86
86
88
87
91
87
87
82
83
83
74
74
79
83
66
80
83
86
87
95
68
80
86
86
78
88
94
74
82
84
89
87
82
96
77
68
93
91
86
94
90
77
91
78
96
97
87
97
77
85
82
90
80
78
86
86
81
46
99
92
81
91
81
92
64
83
70
78
88
98
96
93
91
81
95
93
91
82
84
66
68
82
82
83
76
91
90
79
92
86
83
75
83
91
91
82
78
67
94
77
83
83
69
72
91
86
92
88
86
82
85
92
79
81
88
9

In [125]:
df_점포=pd.concat([e,f,g,h],axis=0)
df_점포.shape

(562808, 12)

In [127]:
df_점포.isna().sum()

기준_년분기_코드      0
행정동_코드         0
행정동_코드_명       0
서비스_업종_코드      0
서비스_업종_코드_명    0
점포_수           0
유사_업종_점포_수     0
개업_율           0
개업_점포_수        0
폐업_률           0
폐업_점포_수        0
프랜차이즈_점포_수     0
dtype: int64

In [176]:
df_total_2=df_점포.copy()

In [177]:
df_total_2

기준_년분기_코드    행정동_코드 행정동_코드_명 서비스_업종_코드 서비스_업종_코드_명  점포_수  유사_업종_점포_수  \
0           20191  11110515    청운효자동  CS100001       한식음식점    82          83   
1           20191  11110515    청운효자동  CS100002       중식음식점     4           4   
2           20191  11110515    청운효자동  CS100003       일식음식점    13          13   
3           20191  11110515    청운효자동  CS100004       양식음식점    36          36   
4           20191  11110515    청운효자동  CS100005         제과점    16          18   
...           ...       ...      ...       ...         ...   ...         ...   
141329      20224  11740700     둔촌2동  CS300038       자동차부품     7           8   
141330      20224  11740700     둔촌2동  CS300039    모터사이클및부품     3           3   
141331      20224  11740700     둔촌2동  CS300041         예술품     3           3   
141332      20224  11740700     둔촌2동  CS300042         주유소     5           5   
141333      20224  11740700     둔촌2동  CS300043      전자상거래업   108         108   

        개업_율  개업_점포_수  폐업_률  폐업_점포_수  프랜차이즈_점포_수  
0          2        2     2        2           1  
1          0        0     0        0           0  
2          0        0     0        0           0  
3          8        3     8        3           0  
4          6        1     0        0           2  
...      ...      ...   ...      ...         ...  
141329     0        0     0        0           1  
141330     0        0     0        0           0  
141331     0        0     0        0           0  
141332     0        0     0        0           0  
141333     0        0     3        3           0  

[562808 rows x 12 columns]