In [1]:

# 행정동 데이터 전처리요~


In [2]:
import numpy as np
import pandas as pd
import os
from glob import glob


In [3]:
df_total=pd.DataFrame()

df_거주인구=pd.DataFrame()
df_상주인구=pd.DataFrame()
df_생활인구=pd.DataFrame()
df_소득소비=pd.DataFrame()
df_아파트=pd.DataFrame()
df_영역=pd.DataFrame()
df_점포=pd.DataFrame()
df_직장인구=pd.DataFrame()
df_집객시설=pd.DataFrame()
df_추정매출=pd.DataFrame()
df_학교=pd.DataFrame()



In [4]:
path='../../../big_proj/data/raw data/행정동/'


In [5]:
pwd

'c:\\Users\\user\\big_proj\\project-file\\Modeling'

In [6]:
# 거주인구
dfs_거주인구=[]
for f_name in glob(path+'거주인구/*.csv'):
    temp=pd.read_csv(f_name)
    dfs_거주인구.append(temp)
    # df_거주인구=pd.concat([df_거주인구,temp],)
a,b,c,d=dfs_거주인구

print(a.shape,b.shape,c.shape,d.shape)


(452, 15) (453, 15) (454, 15) (454, 15)


In [7]:
a.isna().sum()

동별(1)      0
동별(2)      0
동별(3)      0
2019       0
2019.1     0
2019.2     0
2019.3     0
2019.4     0
2019.5     0
2019.6     0
2019.7     0
2019.8     0
2019.9     0
2019.10    0
2019.11    0
dtype: int64

In [8]:
b.isna().sum()

동별(1)      0
동별(2)      0
동별(3)      0
2020       0
2020.1     0
2020.2     0
2020.3     0
2020.4     0
2020.5     0
2020.6     0
2020.7     0
2020.8     0
2020.9     0
2020.10    0
2020.11    0
dtype: int64

In [9]:
c.isna().sum()

동별(1)      0
동별(2)      0
동별(3)      0
2021       0
2021.1     0
2021.2     0
2021.3     0
2021.4     0
2021.5     0
2021.6     0
2021.7     0
2021.8     0
2021.9     0
2021.10    0
2021.11    0
dtype: int64

In [10]:
d.isna().sum()

동별(1)      0
동별(2)      0
동별(3)      0
2022       0
2022.1     0
2022.2     0
2022.3     0
2022.4     0
2022.5     0
2022.6     0
2022.7     0
2022.8     0
2022.9     0
2022.10    0
2022.11    0
dtype: int64

In [11]:
# 상주인구
dfs_상주인구=[]
for f_name in glob(path+'상주인구/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_상주인구.append(temp)
df_상주인구,=dfs_상주인구

df_상주인구.head()

기준_년분기_코드    행정동_코드 행정동_코드_명  총_상주인구_수  남성_상주인구_수  여성_상주인구_수  \
0      20191  11110515    청운효자동     13047       6111       6936   
1      20191  11110530      사직동      9224       4169       5055   
2      20191  11110540      삼청동      2831       1344       1487   
3      20191  11110550      부암동     10055       4850       5205   
4      20191  11110560      평창동     18615       8775       9840   

   연령대_10_상주인구_수  연령대_20_상주인구_수  연령대_30_상주인구_수  연령대_40_상주인구_수  ...  \
0           2248           1648           1879           2304  ...   
1           1387           1095           1383           1558  ...   
2            340            336            422            399  ...   
3           1490           1394           1277           1647  ...   
4           3018           2691           2303           2848  ...   

   남성연령대_60_이상_상주인구_수  여성연령대_10_상주인구_수  여성연령대_20_상주인구_수  여성연령대_30_상주인구_수  \
0                1235             1052              821             1020   
1                1021              697              603              781   
2                 383              156              171              220   
3                1137              689              633              672   
4                1976             1472             1272             1231   

   여성연령대_40_상주인구_수  여성연령대_50_상주인구_수  여성연령대_60_이상_상주인구_수  총_가구_수  아파트_가구_수  \
0             1283             1062                1698    5384       314   
1              856              810                1308    4352       163   
2              201              253                 486    1413         0   
3              905              909                1397    4243        74   
4             1592             1757                2516    7463       459   

   비_아파트_가구_수  
0        5070  
1        4189  
2        1413  
3        4169  
4        7004  

[5 rows x 27 columns]

In [12]:
df_상주인구.shape

(7629, 27)

In [13]:
temp=df_상주인구.loc[df_상주인구['행정동_코드']==11110515]
temp

기준_년분기_코드    행정동_코드 행정동_코드_명  총_상주인구_수  남성_상주인구_수  여성_상주인구_수  \
0         20191  11110515    청운효자동     13047       6111       6936   
418       20192  11110515    청운효자동     13030       6109       6921   
836       20193  11110515    청운효자동     13030       6109       6921   
1254      20194  11110515    청운효자동     12817       5963       6854   
1679      20201  11110515    청운효자동     12817       5963       6854   
2239      20202  11110515    청운효자동     12817       5963       6854   
2529      20203  11110515    청운효자동     12817       5963       6854   
2954      20204  11110515    청운효자동     12434       5780       6654   
3379      20211  11110515    청운효자동     12434       5780       6654   
3533      20212  11110515    청운효자동     12434       5780       6654   
3958      20213  11110515    청운효자동     12434       5780       6654   
4060      20214  11110515    청운효자동     12434       5780       6654   
4485      20221  11110515    청운효자동     12434       5780       6654   
4910      20222  11110515    청운효자동     12434       5780       6654   
5335      20224  11110515    청운효자동     13009       6104       6905   
6179      20232  11110515    청운효자동     13009       6104       6905   
6583      20231  11110515    청운효자동     13009       6104       6905   
6603      20223  11110515    청운효자동     12434       5780       6654   

      연령대_10_상주인구_수  연령대_20_상주인구_수  연령대_30_상주인구_수  연령대_40_상주인구_수  ...  \
0              2248           1648           1879           2304  ...   
418            2288           1641           1883           2314  ...   
836            2288           1641           1883           2314  ...   
1254           2171           1630           1765           2276  ...   
1679           2171           1630           1765           2276  ...   
2239           2171           1630           1765           2276  ...   
2529           2171           1630           1765           2276  ...   
2954           1993           1594           1697           2148  ...   
3379           1993           1594           1697           2148  ...   
3533           1993           1594           1697           2148  ...   
3958           1993           1594           1697           2148  ...   
4060           1993           1594           1697           2148  ...   
4485           1993           1594           1697           2148  ...   
4910           1993           1594           1697           2148  ...   
5335           1650           1622           1661           2151  ...   
6179           1650           1622           1661           2151  ...   
6583           1650           1622           1661           2151  ...   
6603           1993           1594           1697           2148  ...   

      남성연령대_60_이상_상주인구_수  여성연령대_10_상주인구_수  여성연령대_20_상주인구_수  여성연령대_30_상주인구_수  \
0                   1235             1052              821             1020   
418                 1228             1070              812             1023   
836                 1228             1070              812             1023   
1254                1259             1035              836              946   
1679                1259             1035              836              946   
2239                1259             1035              836              946   
2529                1259             1035              836              946   
2954                1275              947              801              917   
3379                1275              947              801              917   
3533                1275              947              801              917   
3958                1275              947              801              917   
4060                1275              947              801              917   
4485                1275              947              801              917   
4910                1275              947              801              917   
5335                1608              783              778              877   
6179                160

In [14]:
df_상주인구['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194, 20201, 20202, 20203, 20204, 20211,
       20212, 20213, 20214, 20221, 20222, 20224, 20231, 20232, 20223],
      dtype=int64)

In [15]:
df_상주인구.isna().sum()

기준_년분기_코드             0
행정동_코드                0
행정동_코드_명              0
총_상주인구_수              0
남성_상주인구_수             0
여성_상주인구_수             0
연령대_10_상주인구_수         0
연령대_20_상주인구_수         0
연령대_30_상주인구_수         0
연령대_40_상주인구_수         0
연령대_50_상주인구_수         0
연령대_60_이상_상주인구_수      0
남성연령대_10_상주인구_수       0
남성연령대_20_상주인구_수       0
남성연령대_30_상주인구_수       0
남성연령대_40_상주인구_수       0
남성연령대_50_상주인구_수       0
남성연령대_60_이상_상주인구_수    0
여성연령대_10_상주인구_수       0
여성연령대_20_상주인구_수       0
여성연령대_30_상주인구_수       0
여성연령대_40_상주인구_수       0
여성연령대_50_상주인구_수       0
여성연령대_60_이상_상주인구_수    0
총_가구_수                0
아파트_가구_수              0
비_아파트_가구_수            0
dtype: int64

In [16]:
df_total=df_상주인구.copy()
df_total.shape

(7629, 27)

In [17]:
# 생활인구
dfs_생활인구=[]
for f_name in glob(path+'생활인구/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_생활인구.append(temp)
df_생활인구,=dfs_생활인구


In [18]:
df_생활인구.shape

(7650, 25)

In [19]:
df_생활인구['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194, 20201, 20202, 20203, 20204, 20211,
       20212, 20213, 20214, 20221, 20222, 20223, 20224, 20231, 20232],
      dtype=int64)

In [20]:
df_생활인구.isna().sum()

기준_년분기_코드           0
행정동_코드              0
행정동_코드_명            0
총_유동인구_수            0
남성_유동인구_수           0
여성_유동인구_수           0
연령대_10_유동인구_수       0
연령대_20_유동인구_수       0
연령대_30_유동인구_수       0
연령대_40_유동인구_수       0
연령대_50_유동인구_수       0
연령대_60_이상_유동인구_수    0
시간대_00_06_유동인구_수    0
시간대_06_11_유동인구_수    0
시간대_11_14_유동인구_수    0
시간대_14_17_유동인구_수    0
시간대_17_21_유동인구_수    0
시간대_21_24_유동인구_수    0
월요일_유동인구_수          0
화요일_유동인구_수          0
수요일_유동인구_수          0
목요일_유동인구_수          0
금요일_유동인구_수          0
토요일_유동인구_수          0
일요일_유동인구_수          0
dtype: int64

In [21]:
temp=df_생활인구.loc[df_생활인구['행정동_코드']==11110515]
temp

기준_년분기_코드    행정동_코드 행정동_코드_명  총_유동인구_수  남성_유동인구_수  여성_유동인구_수  \
360       20191  11110515    청운효자동   3668225    1693148    1975079   
723       20192  11110515    청운효자동   2552571    1157369    1395202   
1057      20193  11110515    청운효자동   3803370    1748586    2054785   
1676      20194  11110515    청운효자동   3979444    1797460    2181985   
1983      20201  11110515    청운효자동   3612274    1704308    1907968   
2293      20202  11110515    청운효자동   3706408    1715282    1991127   
2907      20203  11110515    청운효자동   3670575    1699293    1971283   
3221      20204  11110515    청운효자동   3649597    1683125    1966473   
3532      20211  11110515    청운효자동   3668598    1696887    1971712   
4146      20212  11110515    청운효자동   3759011    1695356    2063656   
4464      20213  11110515    청운효자동   3595242    1639760    1955482   
5097      20214  11110515    청운효자동   3782102    1707702    2074399   
5407      20221  11110515    청운효자동   3627519    1647778    1979740   
5726      20222  11110515    청운효자동   3938615    1678604    2260011   
6332      20223  11110515    청운효자동   3606790    1548951    2057839   
6653      20224  11110515    청운효자동   3710225    1568711    2141514   
7022      20231  11110515    청운효자동   3555653    1537073    2018579   
7479      20232  11110515    청운효자동   3662829    1540083    2122746   

      연령대_10_유동인구_수  연령대_20_유동인구_수  연령대_30_유동인구_수  연령대_40_유동인구_수  ...  \
360          604553         542715         581784         682867  ...   
723          485341         370090         394789         465561  ...   
1057         651565         565357         598555         698489  ...   
1676         674876         580021         604453         721973  ...   
1983         548741         545805         566771         676320  ...   
2293         605224         543934         589086         693868  ...   
2907         603464         528444         575828         677972  ...   
3221         614664         513631         571066         663192  ...   
3532         640867         509125         561721         671692  ...   
4146         682411         524261         568601         685088  ...   
4464         611455         517884         548255         654817  ...   
5097         666893         555016         581038         674667  ...   
5407         625082         528086         567738         644555  ...   
5726         744351         561926         594553         671271  ...   
6332         671537         493363         539709         631875  ...   
6653         729145         504040         542640         648006  ...   
7022         651642         482379         536397         635813  ...   
7479         755955         489936         538071         628500  ...   

      시간대_14_17_유동인구_수  시간대_17_21_유동인구_수  시간대_21_24_유동인구_수  월요일_유동인구_수  \
360             460874            558750            434296      528566   
723             333801            388284            292582      370129   
1057            487289            589105            449141      549173   
1676            518901            644509            465984      570696   
1983            434936            569144            444972      513441   
2293            452553            583690            454883      527864   
2907            440518            575214            452325      526329   
3221            444952            566767            445471      525425   
3532            441865            572620            452862      524347   
4146            466291            590124            455354      540123   
4464            477991            595149            431209      521525   
5097            531963            639961            441128      535719   
5407            500252            612787            427291      517921   
5726            577145            653366            437870      569655   
6332            499607            600505            420329      514855   
6653            528206            612618            424010      524462   
7022            492730       

In [22]:
pd.set_option('display.max_rows', 30)

In [23]:
temp_total=0
cnt=0
for x in df_생활인구['기준_년분기_코드'].unique():
    print("년분기:",x,end='  ')
    print(df_생활인구.loc[df_생활인구['기준_년분기_코드']==x]['기준_년분기_코드'].count(),end='  ')
    if cnt%7==0:
        print()
    cnt+=1
print("cnt:",cnt)

년분기: 20191  425  
년분기: 20192  425  년분기: 20193  425  년분기: 20194  425  년분기: 20201  425  년분기: 20202  425  년분기: 20203  425  년분기: 20204  425  
년분기: 20211  425  년분기: 20212  425  년분기: 20213  425  년분기: 20214  425  년분기: 20221  425  년분기: 20222  425  년분기: 20223  425  
년분기: 20224  425  년분기: 20231  425  년분기: 20232  425  cnt: 18


In [24]:
temp_total=0
cnt=0
for x in df_상주인구['기준_년분기_코드'].unique():
    print("년분기:",x,end='  ')
    print(df_상주인구.loc[df_상주인구['기준_년분기_코드']==x]['기준_년분기_코드'].count(),end='  ')
    if cnt%7==0:
        print()
    cnt+=1
print("cnt:",cnt)

년분기: 20191  418  
년분기: 20192  418  년분기: 20193  418  년분기: 20194  425  년분기: 20201  425  년분기: 20202  425  년분기: 20203  425  년분기: 20204  425  
년분기: 20211  425  년분기: 20212  425  년분기: 20213  425  년분기: 20214  425  년분기: 20221  425  년분기: 20222  425  년분기: 20224  425  
년분기: 20231  425  년분기: 20232  425  년분기: 20223  425  cnt: 18


In [25]:
# 20191, 20192, 20193
dong_code_20191=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20191]['행정동_코드'])
dong_code_20192=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20192]['행정동_코드'])
dong_code_20193=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20193]['행정동_코드'])
dong_code_20194=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20194]['행정동_코드'])

In [26]:
diff_191=[x for x in dong_code_20194 if x not in dong_code_20191 ]
diff_192=[x for x in dong_code_20194 if x not in dong_code_20192 ]
diff_193=[x for x in dong_code_20194 if x not in dong_code_20193 ]
print(diff_191)
print(diff_192)
print(diff_193)
# 번1,2,3동/ 수유1,2,3동/ 항동

[11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800]
[11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800]
[11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800]


In [27]:
# 생활인구 merge
df_total=pd.merge(df_생활인구,df_total,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])

In [28]:
df_total.shape

(7650, 49)

In [29]:
# 소득소비
dfs_소득소비=[]
for f_name in glob(path+'소득소비/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_소득소비.append(temp)
df_소득소비,=dfs_소득소비

In [30]:
df_소득소비.shape

(7650, 16)

In [31]:
df_소득소비.isna().sum()

기준_년분기_코드       0
행정동_코드          0
행정동_코드_명        0
월_평균_소득_금액      0
소득_구간_코드        0
지출_총금액          0
식료품_지출_총금액      0
의류_신발_지출_총금액    0
생활용품_지출_총금액     0
의료비_지출_총금액      0
교통_지출_총금액       0
교육_지출_총금액       0
유흥_지출_총금액       0
여가_문화_지출_총금액    0
기타_지출_총금액       0
음식_지출_총금액       0
dtype: int64

In [32]:
# 소득소비 merge
df_total=pd.merge(df_total,df_소득소비,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])

In [33]:
df_total.shape

(7650, 62)

In [34]:
# 아파트
dfs_아파트=[]
for f_name in glob(path+'아파트/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_아파트.append(temp)
df_아파트,=dfs_아파트

In [35]:
df_아파트.shape

(6368, 18)

In [36]:
df_아파트.isna().sum()

기준_년분기_코드                    0
행정동_코드                       0
행정동_코드_명                     0
아파트_단지_수                     0
아파트_면적_66_제곱미터_미만_세대_수      74
아파트_면적_66_제곱미터_세대_수          3
아파트_면적_99_제곱미터_세대_수        123
아파트_면적_132_제곱미터_세대_수      1126
아파트_면적_165_제곱미터_세대_수      2989
아파트_가격_1_억_미만_세대_수         563
아파트_가격_1_억_세대_수            298
아파트_가격_2_억_세대_수            241
아파트_가격_3_억_세대_수            248
아파트_가격_4_억_세대_수            682
아파트_가격_5_억_세대_수           1368
아파트_가격_6_억_이상_세대_수        2090
아파트_평균_면적                    0
아파트_평균_시가                    0
dtype: int64

In [37]:
temp_=list(df_아파트['기준_년분기_코드'].unique())
sorted(temp_)


[20194,
 20201,
 20202,
 20203,
 20204,
 20211,
 20212,
 20213,
 20214,
 20221,
 20222,
 20223,
 20224,
 20231,
 20232]

In [38]:
# 아파트 merge
df_total=pd.merge(df_total,df_아파트,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])

In [39]:
df_total.shape

(7650, 77)

In [40]:
# 영역
dfs_영역=[]
for f_name in glob(path+'영역/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_영역.append(temp)
df_영역,=dfs_영역

In [41]:
df_영역.shape

(425, 5)

In [42]:
df_영역

행정동_코드  행정동_명  엑스좌표_값  와이좌표_값    영역_면적
0    11110515  청운효자동  197342  453874  2568432
1    11110530    사직동  197383  452705  1158536
2    11110540    삼청동  198340  454312  1479255
3    11110550    부암동  196781  455266  2274739
4    11110560    평창동  197186  457344  8947328
..        ...    ...     ...     ...      ...
420  11740700   둔촌2동  213015  447989  1550455
421  11740640   성내1동  211097  447696   663675
422  11740650   성내2동  211287  448330   625147
423  11740660   성내3동  211824  447659   647356
424  11740685     길동  212900  448920  1631616

[425 rows x 5 columns]

In [43]:
# 점포
dfs_점포=[]
for f_name in glob(path+'점포/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_점포.append(temp)
e,f,g,h=dfs_점포

In [44]:
e.shape,f.shape,g.shape,h.shape

((139799, 12), (140538, 12), (141137, 12), (141334, 12))

In [83]:
columns_equal = all(e.columns == f.columns)
columns_equal

True

In [84]:
columns_equal = all(g.columns == h.columns)
columns_equal

True

In [46]:
e['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194], dtype=int64)

In [47]:
e_1=e.loc[e['기준_년분기_코드']==20191]
e_2=e.loc[e['기준_년분기_코드']==20192]
e_3=e.loc[e['기준_년분기_코드']==20193]
e_4=e.loc[e['기준_년분기_코드']==20194]

In [48]:
f['기준_년분기_코드'].unique()

array([20201, 20202, 20203, 20204], dtype=int64)

In [49]:
f_1=f.loc[f['기준_년분기_코드']==20201]
f_2=f.loc[f['기준_년분기_코드']==20202]
f_3=f.loc[f['기준_년분기_코드']==20203]
f_4=f.loc[f['기준_년분기_코드']==20204]

In [50]:
g['기준_년분기_코드'].unique()

array([20211, 20212, 20213, 20214], dtype=int64)

In [51]:
g_1=g.loc[g['기준_년분기_코드']==20211]
g_2=g.loc[g['기준_년분기_코드']==20212]
g_3=g.loc[g['기준_년분기_코드']==20213]
g_4=g.loc[g['기준_년분기_코드']==20214]

In [52]:
h['기준_년분기_코드'].unique()

array([20221, 20222, 20223, 20224], dtype=int64)

In [53]:
h_1=h.loc[h['기준_년분기_코드']==20221]
h_2=h.loc[h['기준_년분기_코드']==20222]
h_3=h.loc[h['기준_년분기_코드']==20223]
h_4=h.loc[h['기준_년분기_코드']==20224]

In [54]:
len(e_1['행정동_코드'].unique()),len(e_2['행정동_코드'].unique()),len(e_3['행정동_코드'].unique()),len(e_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [55]:
len(f_1['행정동_코드'].unique()),len(f_2['행정동_코드'].unique()),len(f_3['행정동_코드'].unique()),len(f_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [56]:
len(g_1['행정동_코드'].unique()),len(g_2['행정동_코드'].unique()),len(g_3['행정동_코드'].unique()),len(g_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [57]:
len(h_1['행정동_코드'].unique()),len(h_2['행정동_코드'].unique()),len(h_3['행정동_코드'].unique()),len(h_4['행정동_코드'].unique())

(425, 425, 425, 425)

In [58]:
e_1.shape,e_2.shape,e_3.shape,e_4.shape

((34853, 12), (34925, 12), (34987, 12), (35034, 12))

In [59]:
df_점포=pd.concat([e,f,g,h],axis=0)
df_점포.shape

(562808, 12)

In [60]:
df_점포.isna().sum()

기준_년분기_코드      0
행정동_코드         0
행정동_코드_명       0
서비스_업종_코드      0
서비스_업종_코드_명    0
점포_수           0
유사_업종_점포_수     0
개업_율           0
개업_점포_수        0
폐업_률           0
폐업_점포_수        0
프랜차이즈_점포_수     0
dtype: int64

In [61]:
df_total_2=df_점포.copy()

In [63]:
df_total_2.shape

(562808, 12)

In [64]:
# 직장인구
dfs_직장인구=[]
for f_name in glob(path+'직장인구/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_직장인구.append(temp)
df_직장인구,=dfs_직장인구

In [65]:
df_직장인구.shape

(7636, 24)

In [66]:
df_직장인구.isna().sum()

기준_년분기_코드              0
행정동_코드                 0
행정동_코드_명               0
총_직장_인구_수              0
남성_직장_인구_수             0
여성_직장_인구_수             0
연령대_10_직장_인구_수         0
연령대_20_직장_인구_수         0
연령대_30_직장_인구_수         0
연령대_40_직장_인구_수         0
연령대_50_직장_인구_수         0
연령대_60_이상_직장_인구_수      0
남성연령대_10_직장_인구_수       0
남성연령대_20_직장_인구_수       0
남성연령대_30_직장_인구_수       0
남성연령대_40_직장_인구_수       0
남성연령대_50_직장_인구_수       0
남성연령대_60_이상_직장_인구_수    0
여성연령대_10_직장_인구_수       0
여성연령대_20_직장_인구_수       0
여성연령대_30_직장_인구_수       0
여성연령대_40_직장_인구_수       0
여성연령대_50_직장_인구_수       0
여성연령대_60_이상_직장_인구_수    0
dtype: int64

In [67]:
temp_total=0
cnt=0
for x in df_직장인구['기준_년분기_코드'].unique():
    print("년분기:",x,end='  ')
    print(df_직장인구.loc[df_직장인구['기준_년분기_코드']==x]['기준_년분기_코드'].count(),end='  ')
    if cnt%7==0:
        print()
    cnt+=1
print("cnt:",cnt)

년분기: 20191  425  
년분기: 20192  418  년분기: 20193  418  년분기: 20194  425  년분기: 20201  425  년분기: 20202  425  년분기: 20203  425  년분기: 20211  425  
년분기: 20212  425  년분기: 20213  425  년분기: 20221  425  년분기: 20222  425  년분기: 20223  425  년분기: 20231  425  년분기: 20232  425  
년분기: 20224  425  년분기: 20204  425  년분기: 20214  425  cnt: 18


In [68]:
dong_code_직장_20192=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20192]['행정동_코드'])
diff_직장_192=[x for x in dong_code_20194 if x not in dong_code_직장_20192 ]

In [69]:
dong_code_직장_20193=list(df_상주인구.loc[df_상주인구['기준_년분기_코드']==20193]['행정동_코드'])
diff_직장_193=[x for x in dong_code_20194 if x not in dong_code_직장_20193 ]

In [70]:
diff_직장_192,diff_직장_193
# 번1,2,3동/ 수유1,2,3동/ 항동

([11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800],
 [11305595, 11305603, 11305608, 11305615, 11305625, 11305635, 11530800])

In [71]:
# 직장인구 merge
df_total=pd.merge(df_total,df_직장인구,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])
df_total.shape

(7650, 98)

In [73]:
# 집객시설
dfs_집객시설=[]
for f_name in glob(path+'집객시설/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_집객시설.append(temp)
df_집객시설,=dfs_집객시설
df_집객시설.shape

(4675, 23)

In [74]:
temp_total=0
cnt=0
for x in df_집객시설['기준_년분기_코드'].unique():
    print("년분기:",x,end='  ')
    print(df_집객시설.loc[df_집객시설['기준_년분기_코드']==x]['기준_년분기_코드'].count(),end='  ')
    if cnt%7==0:
        print()
    cnt+=1
print("cnt:",cnt)

년분기: 20232  425  
년분기: 20231  425  년분기: 20204  425  년분기: 20214  425  년분기: 20211  425  년분기: 20212  425  년분기: 20221  425  년분기: 20222  425  
년분기: 20213  425  년분기: 20223  425  년분기: 20224  425  cnt: 11


In [75]:
# 집객시설 merge
df_total=pd.merge(df_total,df_집객시설,how='left',on=['기준_년분기_코드','행정동_코드','행정동_코드_명'])
df_total.shape

(7650, 118)

In [76]:
# 추정매출
dfs_추정매출=[]
for f_name in glob(path+'추정매출/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_추정매출.append(temp)
i,j,k,l=dfs_추정매출

In [77]:
i.shape,j.shape,k.shape,l.shape

((65758, 53), (66583, 53), (67111, 53), (67748, 53))

In [81]:
columns_equal = all(i.columns == j.columns)
columns_equal


True

In [82]:
columns_equal = all(k.columns == l.columns)
columns_equal

True

In [85]:
i['기준_년분기_코드'].unique()

array([20191, 20192, 20193, 20194], dtype=int64)

In [86]:
i_1=i.loc[i['기준_년분기_코드']==20191]
i_2=i.loc[i['기준_년분기_코드']==20192]
i_3=i.loc[i['기준_년분기_코드']==20193]
i_4=i.loc[i['기준_년분기_코드']==20194]

In [87]:
j['기준_년분기_코드'].unique()

array([20201, 20202, 20203, 20204], dtype=int64)

In [88]:
j_1=j.loc[j['기준_년분기_코드']==20201]
j_2=j.loc[j['기준_년분기_코드']==20202]
j_3=j.loc[j['기준_년분기_코드']==20203]
j_4=j.loc[j['기준_년분기_코드']==20204]

In [89]:
k['기준_년분기_코드'].unique()

array([20211, 20212, 20213, 20214], dtype=int64)

In [90]:
k_1=k.loc[k['기준_년분기_코드']==20211]
k_2=k.loc[k['기준_년분기_코드']==20212]
k_3=k.loc[k['기준_년분기_코드']==20213]
k_4=k.loc[k['기준_년분기_코드']==20214]

In [91]:
l['기준_년분기_코드'].unique()

array([20221, 20222, 20223, 20224], dtype=int64)

In [92]:
l_1=l.loc[l['기준_년분기_코드']==20221]
l_2=l.loc[l['기준_년분기_코드']==20222]
l_3=l.loc[l['기준_년분기_코드']==20223]
l_4=l.loc[l['기준_년분기_코드']==20224]

In [93]:
len(i_1['행정동_코드'].unique()),len(i_2['행정동_코드'].unique()),len(i_3['행정동_코드'].unique()),len(i_4['행정동_코드'].unique())

(423, 423, 423, 423)

In [94]:
len(j_1['행정동_코드'].unique()),len(j_2['행정동_코드'].unique()),len(j_3['행정동_코드'].unique()),len(j_4['행정동_코드'].unique())

(423, 423, 423, 423)

In [95]:
len(k_1['행정동_코드'].unique()),len(k_2['행정동_코드'].unique()),len(k_3['행정동_코드'].unique()),len(k_4['행정동_코드'].unique())

(423, 423, 423, 423)

In [96]:
len(l_1['행정동_코드'].unique()),len(l_2['행정동_코드'].unique()),len(l_3['행정동_코드'].unique()),len(l_4['행정동_코드'].unique())

(423, 424, 424, 424)

In [97]:
i_1.shape,i_2.shape,i_3.shape,i_4.shape,j_1.shape,j_2.shape,j_3.shape,j_4.shape,k_1.shape,k_2.shape,k_3.shape,k_4.shape,l_1.shape,l_2.shape,l_3.shape,l_4.shape

((16298, 53),
 (16436, 53),
 (16471, 53),
 (16553, 53),
 (16525, 53),
 (16678, 53),
 (16695, 53),
 (16685, 53),
 (16640, 53),
 (16798, 53),
 (16806, 53),
 (16867, 53),
 (16830, 53),
 (16934, 53),
 (16976, 53),
 (17008, 53))

In [103]:
# 추정매출 합치기
df_추정매출=pd.concat([i,j,k,l],axis=0)
df_추정매출.shape


(267200, 53)

In [111]:
# merge (outer join)
df_total_2=pd.merge(df_total_2,df_추정매출,how='left',on=['기준_년분기_코드', '행정동_코드', '행정동_코드_명', '서비스_업종_코드', '서비스_업종_코드_명'])
df_total_2.shape

(562808, 60)

In [112]:
# 학교
dfs_학교=[]
for f_name in glob(path+'학교/*.csv'):
    temp=pd.read_csv(f_name,encoding='cp949')
    dfs_학교.append(temp)
df_학교,=dfs_학교
df_학교.shape

(3932, 28)

In [113]:
df_학교

학교종류명 설립구분   표준학교코드                   학교명  \
0     각종학교(중)   사립  7134155               선화예술중학교   
1        초등학교   공립  7134150              서울숭신초등학교   
2         중학교   공립  7134142                 행당중학교   
3         중학교   사립  7134141        한양대학교사범대학부속중학교   
4         중학교   공립  7134140                 자양중학교   
...       ...  ...      ...                   ...   
3927     고등학교   국립  1371661              국립국악고등학교   
3928     특수학교   국립  1342102                한국우진학교   
3929     특수학교   국립  1342099                 서울농학교   
3930     특수학교   국립  1342098                 서울맹학교   
3931    공동실습소   공립        0  경기기계공업고등학교부설미래기술교육센터   

                                    영문학교명           관할조직명  도로명우편번호  \
0               Sunhwa Arts Middle School  서울특별시성동광진교육지원청     4991   
1       Seoul Soongshin Elementary School  서울특별시성동광진교육지원청     4702   
2                 Haengdang Middle School  서울특별시성동광진교육지원청     4764   
3        Hanyang University Middle School  서울특별시성동광진교육지원청     4761   
4                    Jayang Middle School  서울특별시성동광진교육지원청     5069   
...                                   ...             ...      ...   
3927           Gugak National High School             교육부     6311   
3928                 Hanguk Woojin School             교육부     3934   
3929   Seoul National school for the Deaf             교육부     3032   
3930  Seoul National School for the Blind             교육부     3032   
3931                                    .        서울특별시교육청     1810   

                      도로명주소             도로명상세주소          전화번호  ... 주야구분명  \
0        서울특별시 광진구 천호대로 664    / 선화예술중고등학교 (능동)  02-2204-1100  ...    주간   
1         서울특별시 성동구 마장로 161             (하왕십리동)  02-2252-5950  ...    주간   
2        서울특별시 성동구 왕십리로 189         (행당동/행당중학교)  02-2292-2721  ...    주간   
3          서울특별시 성동구 마조로 42  (사근동/한양사대부속중?고등학교)  02-2200-3700  ...    주간   
4       서울특별시 광진구 뚝섬로41길 33       (자양동/서울자양중학교)   02-446-0365  ...    주간   
...                     ...                 ...           ...  ...   ...   
3927    서울특별시 강남구 개포로22길 65       (개포동/ 국악고등학교)  02-3460-0500  ...    주간   
3928  서울특별시 마포구 월드컵북로38길 21       / 한국우진학교 (중동)  02-6388-5800  ...    주간   
3929     서울특별시 종로구 필운대로 103               (신교동)   02-737-0659  ...    주간   
3930      서울특별시 종로구 필운대로 97               (신교동)   02-731-6772  ...    주간   
3931      서울특별시 노원구 공릉로 264   (하계동/ 경기기계공업고등학교)   02-970-8922  ...    주간   

          설립일자     개교기념일 시도교육청코드    시도교육청명   소재지명 주야과정      계열명    학과명  \
0     19731201  19730705     B10  서울특별시교육청  서울특별시  NaN      NaN    NaN   
1     19590403  19590403     B10  서울특별시교육청  서울특별시  NaN      NaN    NaN   
2     19680806  19681002     B10  서울특별시교육청  서울특별시  NaN      NaN    NaN   
3     19600118  19600118     B10  서울특별시교육청  서울특별시  NaN      NaN    NaN   
4     19840301  19840301     B10  서울특별시교육청  서울특별시  NaN      NaN    NaN   
...        ...       ...     ...       ...    ...  ...      ...    ...   
3927  19550401  19720909     B10  서울특별시교육청  서울특별시   주간      예술계    무용과   
3928  20000301  20000306     B10  서울특별시교육청  서울특별시  NaN      NaN    NaN   
3929  19130401  19130401     B10  서울특별시교육청  서울특별시  NaN      NaN    NaN   
3930  19130401  19130401     B10  서울특별시교육청  서울특별시  NaN      NaN    NaN   
3931  19820601  19820601     B10  서울특별시교육청  서울특별시   주간  기계공동실습소  공동실습소   

                적재일시  
0     20230627000000  
1     20230615000000  
2     20230615000000  
3     20230615000000  
4     20230615000000  
...              ...  
3927  20230615000000  
3928  20230709000000  
3929  20230709000000  
3930  20230709000000  
3931  20230615000000  

[3932 rows x 28 columns]

In [119]:
df_total.shape,df_total_2.shape

((7650, 118), (562808, 60))